enum class TokenType {
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, RIGHT_BRACKET, LEFT_BRACKET,
  COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, PLUS_PLUS, MINUS_MINUS,
  PERCENT, AMPERSAND, CARET, VBAR,

  BANG, BANG_EQUAL,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,

  IDENTIFIER, STRING, NUMBER, INCLUDE,

  AND, CLASS, ELSE, FALSE, SET, FOR, IF, NIL, OR, OUT,
  OUTPUT, RETURN, SUPER, THIS, TRUE, AUTO, WHILE,

  TER_EOF 
};

